/**
 * State definitions for Minehunt AI decision engine
 */
const BotState = {
  INITIALIZING: 'INITIALIZING',
  PREPARATION: 'PREPARATION',
  TRACKING: 'TRACKING',
  GATHERING: 'GATHERING',
  CRAFTING: 'CRAFTING',
  EQUIPPING: 'EQUIPPING',
  INTERCEPTING: 'INTERCEPTING',
  CHASE: 'CHASE',
  COMBAT: 'COMBAT',
  RETREAT: 'RETREAT',
  RECOVERY: 'RECOVERY',
  LOOTING: 'LOOTING',
  UPGRADING: 'UPGRADING',
  NETHER_PROGRESS: 'NETHER_PROGRESS',
  ENDGAME_INTERCEPTION: 'ENDGAME_INTERCEPTION',
  SEARCHING: 'SEARCHING',
  TARGET_DEAD: 'TARGET_DEAD',
  FIVE_MINUTE_UPGRADE: 'FIVE_MINUTE_UPGRADE',
  EMERGENCY: 'EMERGENCY'
};

/**
 * Priority levels for actions
 */
const Priority = {
  CRITICAL: 0,
  HIGH: 1,
  MEDIUM: 2,
  LOW: 3
};

module.exports = { BotState, Priority };
